---
- name: Install and configure BetterStack (Vector)
  hosts: all
  become: true
  serial: 10
  vars:
    ansible_root: "{{ playbook_dir }}/.."
    vector_version: "0.46.1"
    vector_config_template: "{{ ansible_root }}/config/templates/vector.yaml.j2"
    vector_deb_path: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
    vector_download_url: "https://github.com/vectordotdev/vector/releases/download/v{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"

  tasks:
    - name: Load secrets file
      include_vars:
        file: "../secrets/{{ env }}/secrets.yaml"
        name: secrets

    - name: Load config file
      include_vars:
        file: "{{ ansible_root }}/config/config.{{ env }}.yaml"
        name: config

    - name: Set other variables
      set_fact:
        betterstack_key: "{{ secrets.BETTERSTACK_KEY }}"
        apymon_env: "{{ config.ENVIRONMENT }}"
        group_name: "{{ config.GROUP_NAME }}"

    - name: Ensure /etc/vector directory exists
      file:
        path: /etc/vector
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Render vector.yaml from template
      template:
        src: "{{ vector_config_template }}"
        dest: /etc/vector/vector.yaml
        owner: root
        group: root
        mode: '0644'


