name: Push Multi-Arch Latest Manifest

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Existing image tag to base :latest off (e.g. testnet-v1.2.3)'
        required: true

jobs:
  push-latest:
    runs-on: snarkos-amd64-builder

    steps:
      - name: Infer NETWORK from tag_name
        id: parse
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          echo "Evaluating tag: $TAG_NAME"
          if [[ "$TAG_NAME" == testnet-* ]]; then
            NETWORK=testnet
          elif [[ "$TAG_NAME" == canary-* ]]; then
            NETWORK=canary
          else
            NETWORK=mainnet
          fi
          echo "network=$NETWORK" >> $GITHUB_OUTPUT
          echo "NETWORK_DIR=$NETWORK" >> $GITHUB_ENV

      - name: Debug network inference
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}"
          echo "Inferred NETWORK=${NETWORK}"

      - name: Export Env Vars
        run: |
          echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "GCP_ARTIFACT_REGISTRY_REGION=${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}" >> $GITHUB_ENV
          echo "GCP_ARTIFACT_REPO=${{ vars.GCP_ARTIFACT_REPO }}" >> $GITHUB_ENV
          echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_SNARKOS_REPO }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push :latest Manifest to GCP and Docker Hub
        run: |
          # GCP
          docker manifest create us-east1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_ARTIFACT_REPO}/${NETWORK_DIR}/snarkos:latest \
            --amend us-east1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_ARTIFACT_REPO}/${NETWORK_DIR}/snarkos:${{ github.event.inputs.tag_name }}-amd64 \
            --amend us-east1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_ARTIFACT_REPO}/${NETWORK_DIR}/snarkos:${{ github.event.inputs.tag_name }}-arm64

          docker manifest push us-east1-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_ARTIFACT_REPO}/${NETWORK_DIR}/snarkos:latest

          # Docker Hub
          docker manifest create ${DOCKERHUB_REPO}:latest \
            --amend ${DOCKERHUB_REPO}:${{ github.event.inputs.tag_name }}-amd64 \
            --amend ${DOCKERHUB_REPO}:${{ github.event.inputs.tag_name }}-arm64

          docker manifest push ${DOCKERHUB_REPO}:latest
