name: Build and Push SnarkOS

on:
  workflow_dispatch:
    inputs:
      git_ref:
        required: false
        default: "c4c76b6"
        type: string
        description: "Git ref (commit/branch/tag) of snarkOS repo to build"
      tag:
        required: true
        type: string
        description: "Docker image tag (e.g. v1.2.3)"
      architectures:
        required: true
        default: "amd64,arm64"
        description: "Comma-separated architectures"
      environment:
        required: true
        default: "canary"
        type: choice
        options:
          - canary
          - testnet
          - mainnet
      project_id:
        required: true
        description: "GCP project ID"
      project_number:
        required: true
        description: "GCP project number"

  push:
    branches:
      - dockerfile

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REF: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.git_ref || (github.event_name == 'push' && 'c4c76b6') }}"
      DOCKER_TAG: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || (github.event_name == 'push' && 'v1.2.3') }}"
      ARCHS: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.architectures || 'amd64 arm64' }}"
      ENVIRONMENT: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'canary' }}"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # only needed for this repo, not snarkOS

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/${{ github.event.inputs.project_number || secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "anf-builder@${{ github.event.inputs.project_id || secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Parse architectures
        id: parse
        run: |
          echo "archs=$(echo '${{ env.ARCHS }}' | tr ',' ' ')" >> $GITHUB_OUTPUT

      - name: Build and Push SnarkOS Docker image
        run: |
          docker buildx create --use

          for arch in ${{ steps.parse.outputs.archs }}; do
            docker buildx build \
              --platform linux/$arch \
              --build-arg GIT_REF=${{ env.GIT_REF }} \
              --build-arg NETWORK=${{ github.event.inputs.environment }} \
              -t us-east1-docker.pkg.dev/${{ github.event.inputs.project_id || secrets.GCP_PROJECT_ID }}/snarkos-containers/${{ env.ENVIRONMENT }}-snarkos:${{ env.DOCKER_TAG }}-$arch
              --push .
          done
