name: Builds and Pushes SnarkOS Boot-Patch Image

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'snarkOS commit SHA or tag'
        required: true

jobs:

  extractor:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release_info.outputs.tag_name }}
      network: ${{ steps.release_info.outputs.network }}
    steps:
      - name: Clone and Extract Info
        id: release_info
        run: |
          git clone https://github.com/ProvableHQ/snarkOS.git snarkos
          cd snarkos
          git checkout ${{ github.event.inputs.git_ref }}
          git fetch --tags

          TAG_NAME=$(git tag --contains ${{ github.event.inputs.git_ref }} | head -n1 || echo "")
          if [[ -z "$TAG_NAME" ]]; then
            echo "No tag found for commit ${{ github.event.inputs.git_ref }}"
            exit 1
          fi
          echo "Extracted tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

          if [[ "$TAG_NAME" == testnet-* ]]; then
            NETWORK="testnet"
          elif [[ "$TAG_NAME" == canary-* ]]; then
            NETWORK="canary"
          else
            NETWORK="mainnet"
          fi
          echo "Extracted network: $NETWORK"
          echo "network=$NETWORK" >> $GITHUB_OUTPUT

  build-boot:
    needs: extractor
    runs-on: snarkos-amd64-builder
    name: Build SnarkOS Boot-Patch Image

    steps:
      - uses: actions/checkout@v4

      - name: Export Environment Variables from GitHub Variables
        run: |
          echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "GCP_ARTIFACT_REGISTRY_REGION=${{ vars.GCP_ARTIFACT_REGISTRY_REGION }}" >> $GITHUB_ENV
          echo "GCP_ARTIFACT_REPO=${{ vars.GCP_ARTIFACT_REPO }}" >> $GITHUB_ENV

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Map NETWORK_NAME
        run: |
          case "${{ needs.extractor.outputs.network }}" in
            mainnet) echo "NETWORK=0" >> $GITHUB_ENV && echo "NETWORK_DIR=mainnet" >> $GITHUB_ENV ;;
            testnet) echo "NETWORK=1" >> $GITHUB_ENV && echo "NETWORK_DIR=testnet" >> $GITHUB_ENV ;;
            canary)  echo "NETWORK=2" >> $GITHUB_ENV && echo "NETWORK_DIR=canary" >> $GITHUB_ENV ;;
            *) echo "Unknown network" && exit 1 ;;
          esac

      - name: Build and Push Boot-Patched Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./service/boot-patch/Dockerfile.boot
          push: true
          platforms: linux/amd64
          provenance: false
          tags: us-east1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/${{ env.NETWORK_DIR }}/snarkos:${{ needs.extractor.outputs.tag_name }}-boot
          build-args: |
            GIT_REF=${{ github.event.inputs.git_ref }}
            NETWORK=${{ env.NETWORK }}
