name: Build and Push Snapshot Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'service/snapshot/**'
      - '.github/workflows/build-snapshot.yml'

env:
  GCP_PROJECT_ID: docker-registry-anf
  GCP_ARTIFACT_REGISTRY_REGION: us-east1
  GCP_ARTIFACT_REPO: snarkos-containers
  IMAGE_TAG: latest

jobs:
  build-snapshot:
    runs-on: snarkos-amd64-builder
    name: Build Snapshot Image

    steps:
      - uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Snapshot Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./service/snapshot/Dockerfile.snapshot
          push: true
          platforms: linux/amd64
          provenance: false
          tags: us-east1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/snapshot:${{ env.IMAGE_TAG }}
