name: Build and Push SnarkOS

on:
  workflow_dispatch:
    inputs:
      git_ref:
        required: false
        default: "c4c76b6"
        type: string
        description: "Git ref to checkout (branch, tag, or SHA)"
      tag:
        required: true
        type: string
        description: "Docker image tag to push (e.g. v1.2.3)"
      architectures:
        required: true
        default: "amd64,arm64"
        description: "Comma-separated arch list"
      environment:
        required: true
        default: "canary"
        type: choice
        options:
          - canary
          - testnet
          - mainnet
      project_id:
        required: true
        description: "GCP project ID to push to"
      project_number:
        required: true
        description: "GCP project NUMBER to use in workload_identity_provider"

  push:
    branches:
      - dockerfile

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REF: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.git_ref || (github.event_name == 'push' && 'c4c76b6') }}"
      DOCKER_TAG: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || (github.event_name == 'push' && 'v1.2.3') }}"
      ARCHS: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.architectures || 'amd64 arm64' }}"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/${{ github.event.inputs.project_number || secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "anf-builder@${{ github.event.inputs.project_id || secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
