name: Build and Push SnarkOS

on:
  workflow_dispatch:
    inputs:
      git_ref:
        required: false
        default: "c4c76b6"
        type: string
        description: "Git ref to checkout (branch, tag, or SHA)"
      tag:
        required: true
        type: string
        description: "Docker image tag to push (e.g. v1.2.3)"
      architectures:
        required: true
        default: "amd64,arm64"
        description: "Comma-separated arch list"
      environment:
        required: true
        default: "canary"
        type: choice
        options:
          - canary
          - testnet
          - mainnet
      project_id:
        required: true
        description: "GCP project ID to push to"
      project_number:
        required: true
        description: "GCP project NUMBER to use in workload_identity_provider"
  push:
    branches:
      - dockerfile
      
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref || github.ref_name }}

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/${{ github.event.inputs.project_number || secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "anf-builder@${{ github.event.inputs.project_id || secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Parse architectures #Updated
        id: parse
        run: |
          echo "archs=$(echo '${{ inputs.architectures }}' | tr ',' ' ')" >> $GITHUB_OUTPUT

      - name: Build and Push SnarkOS Image
        run: |
          docker buildx create --use
          for arch in ${{ steps.parse.outputs.archs }}; do
            docker buildx build \
              --platform linux/$arch \
              --build-arg GIT_REF=${{ github.event.inputs.git_ref || github.ref_name }} \
              --build-arg IMAGE_NAME=ubuntu:24.04 \
              -t us-east1-docker.pkg.dev/${{ github.event.inputs.project_id || secrets.GCP_PROJECT_ID }}/snarkos-containers/${{ inputs.environment }}-snarkos:${{ inputs.tag }}-$arch \
              --push .
          done
